[package]
name = "camel"
version = "0.1.0"
edition = "2021"

[lib]
name = "camel"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.8", features = ["derive"] }
thiserror = "1.0.61"

[dev-dependencies]
rstest = "0.21.0"
